# Move to gladius-network-gateway.toml
# Uncomment to change the gladius base directory
# gladiusbase = "/home/USER/.gladius"

# Use UPNP to discover WAN IP, and open p2p port
upnpenabled = false

[api]
  debugrequests = false
  port = "3001"
  remoteconnectionsallowed = false

# Infura and smart contract configs
[blockchain]
  marketaddress = "0x27a9390283236f836a0b3c8dfdbed2ed854322fc"
  poolmanageraddress = "0x9717EaDbfE344457135a4f1fA8AE3B11B4CAB0b7"
  poolurl = "http://174.138.111.1/api/"
  provider = "https://mainnet.infura.io/v3/1d3545f907ff4598893997c522e46676"

# Change the logger
[log]
  level = "debug"
  pretty = true

[p2p]
  # Tell other nodes how to reach you. If left empty, the Network Gateway will 
  # do detection either with UPNP (if enabled) or an external service
  advertiseaddress = "" # What is advertised as your reachable address
  advertiseport = 7947 # Advertised port
  
  # The interface and port to listen on
  bindaddress = "0.0.0.0" # The interface 
  bindport = 7947

  # Verify if messages are from the pool or not, used in testing
  messageverifyoverride = false

[wallet]
  directory = "/home/user/.gladius/wallet"
  Passphrase = ""

[Pool]
  AutoJoin = false
  URL = "http://localhost:3002/api/"
  Address = "0x0000000000000000000000000000000000000000"

[Profile]
  Name = "Example Node"
  Email = "example@gladius.io"
  Bio = "Example Bio"
  Location = ""
  EstimatedSpeed = 100
